#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${BASH_SOURCE[0]:-}" ]]; then
  script_path="${BASH_SOURCE[0]}"
else
  script_path="$0"
fi

script_dir="$(cd "$(dirname "${script_path}")" && pwd)"
defaults_file="${UDS_POC_DEFAULTS_FILE:-${script_dir}/defaults.env}"

if [[ -f "${defaults_file}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${defaults_file}"
  set +a
fi

UDS_POC_REGISTRY="${UDS_POC_REGISTRY:-localhost:5001}"
UDS_POC_REPOSITORY="${UDS_POC_REPOSITORY:-uds-poc}"
UDS_POC_VERSION="${UDS_POC_VERSION:-0.1.0}"

case "$(uname -m)" in
  arm64|aarch64)
    UDS_POC_ARCH="${UDS_POC_ARCH:-arm64}"
    UDS_POC_DOCKER_PLATFORM="${UDS_POC_DOCKER_PLATFORM:-linux/arm64}"
    ;;
  x86_64|amd64)
    UDS_POC_ARCH="${UDS_POC_ARCH:-amd64}"
    UDS_POC_DOCKER_PLATFORM="${UDS_POC_DOCKER_PLATFORM:-linux/amd64}"
    ;;
  *)
    UDS_POC_ARCH="${UDS_POC_ARCH:-$(uname -m)}"
    UDS_POC_DOCKER_PLATFORM="${UDS_POC_DOCKER_PLATFORM:-linux/$(uname -m)}"
    ;;
esac

UDS_POC_PLAIN_HTTP=false
if [[ "${UDS_POC_REGISTRY}" == localhost:* || "${UDS_POC_REGISTRY}" == 127.0.0.1:* || "${UDS_POC_REGISTRY}" == host.k3d.internal:* ]]; then
  UDS_POC_PLAIN_HTTP=true
fi

UDS_POC_PLATFORM_NAME="${UDS_POC_PLATFORM_NAME:-uds-poc-platform}"
UDS_POC_PLATFORM_NAMESPACE="${UDS_POC_PLATFORM_NAMESPACE:-uds-poc}"
UDS_POC_BACKEND_IMAGE="${UDS_POC_BACKEND_IMAGE:-${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/backend:${UDS_POC_VERSION}}"
UDS_POC_FRONTEND_IMAGE="${UDS_POC_FRONTEND_IMAGE:-${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/frontend:${UDS_POC_VERSION}}"
UDS_POC_PLATFORM_PACKAGE_ARCHIVE="${UDS_POC_PLATFORM_PACKAGE_ARCHIVE:-build/zarf-package-${UDS_POC_PLATFORM_NAME}-${UDS_POC_ARCH}-${UDS_POC_VERSION}.tar.zst}"
UDS_POC_PLATFORM_OCI_REF="${UDS_POC_PLATFORM_OCI_REF:-oci://${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/${UDS_POC_PLATFORM_NAME}:${UDS_POC_VERSION}}"

DOCS_NAME="${DOCS_NAME:-docs}"
DOCS_NAMESPACE="${DOCS_NAMESPACE:-docs}"
DOCS_PACKAGE_DIR="${DOCS_PACKAGE_DIR:-components/docs}"
DOCS_IMAGE="${DOCS_IMAGE:-${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/docs:${UDS_POC_VERSION}}"
DOCS_PACKAGE_ARCHIVE="${DOCS_PACKAGE_ARCHIVE:-build/zarf-package-${DOCS_NAME}-${UDS_POC_ARCH}-${UDS_POC_VERSION}.tar.zst}"
DOCS_OCI_REF="${DOCS_OCI_REF:-oci://${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/${DOCS_NAME}:${UDS_POC_VERSION}}"

CATALOG_POC_NAME="${CATALOG_POC_NAME:-catalog-poc}"
CATALOG_POC_NAMESPACE="${CATALOG_POC_NAMESPACE:-${CATALOG_POC_NAME}}"
CATALOG_POC_ARCH="${CATALOG_POC_ARCH:-${UDS_POC_ARCH}}"
CATALOG_POC_PACKAGE_DIR="${CATALOG_POC_PACKAGE_DIR:-components/catalog-poc}"
CATALOG_POC_BUILD_DIR="${CATALOG_POC_BUILD_DIR:-build/${CATALOG_POC_NAME}}"
CATALOG_POC_IMAGE="${CATALOG_POC_IMAGE:-${UDS_POC_REGISTRY}/${CATALOG_POC_NAME}:${UDS_POC_VERSION}}"
CATALOG_POC_OCI_REF="${CATALOG_POC_OCI_REF:-oci://${UDS_POC_REGISTRY}/${UDS_POC_REPOSITORY}/${CATALOG_POC_NAME}:${UDS_POC_VERSION}}"
CATALOG_POC_PACKAGE_ARCHIVE="${CATALOG_POC_PACKAGE_ARCHIVE:-build/zarf-package-${CATALOG_POC_NAME}-${UDS_POC_ARCH}-${UDS_POC_VERSION}.tar.zst}"

export UDS_POC_ARCH
export UDS_POC_BACKEND_IMAGE
export UDS_POC_DOCKER_PLATFORM
export UDS_POC_FRONTEND_IMAGE
export UDS_POC_PLATFORM_NAME
export UDS_POC_PLATFORM_NAMESPACE
export UDS_POC_PLATFORM_OCI_REF
export UDS_POC_PLATFORM_PACKAGE_ARCHIVE
export UDS_POC_PLAIN_HTTP
export UDS_POC_REGISTRY
export UDS_POC_REPOSITORY
export UDS_POC_VERSION

export DOCS_IMAGE
export DOCS_NAME
export DOCS_NAMESPACE
export DOCS_OCI_REF
export DOCS_PACKAGE_ARCHIVE
export DOCS_PACKAGE_DIR

export CATALOG_POC_IMAGE
export CATALOG_POC_ARCH
export CATALOG_POC_BUILD_DIR
export CATALOG_POC_NAME
export CATALOG_POC_NAMESPACE
export CATALOG_POC_OCI_REF
export CATALOG_POC_PACKAGE_ARCHIVE
export CATALOG_POC_PACKAGE_DIR
