apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
  labels:
    app.kubernetes.io/name: docs
    app.kubernetes.io/component: documentation
    app.kubernetes.io/part-of: uds-local-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docs
        app.kubernetes.io/component: documentation
        app.kubernetes.io/part-of: uds-local-poc
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: docs
          image: localhost:5001/uds-poc/docs:0.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
