apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: docs
  labels:
    app.kubernetes.io/name: docs
    app.kubernetes.io/component: documentation
    app.kubernetes.io/part-of: uds-local-poc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docs
  ports:
    - name: http
      port: 3002
      targetPort: http
