#!/usr/bin/env bash
set -euo pipefail

CATALOG_POC_NAME="${CATALOG_POC_NAME:-catalog-poc}"
CATALOG_POC_VERSION="${CATALOG_POC_VERSION:-0.1.0}"
CATALOG_POC_REGISTRY="${CATALOG_POC_REGISTRY:-localhost:5001}"
CATALOG_POC_REPOSITORY="${CATALOG_POC_REPOSITORY:-uds-poc}"
CATALOG_POC_IMAGE="${CATALOG_POC_IMAGE:-${CATALOG_POC_REGISTRY}/${CATALOG_POC_NAME}:${CATALOG_POC_VERSION}}"
CATALOG_POC_OCI_REF="${CATALOG_POC_OCI_REF:-oci://${CATALOG_POC_REGISTRY}/${CATALOG_POC_REPOSITORY}/${CATALOG_POC_NAME}:${CATALOG_POC_VERSION}}"

case "$(uname -m)" in
  arm64|aarch64)
    CATALOG_POC_ARCH="${CATALOG_POC_ARCH:-arm64}"
    ;;
  x86_64|amd64)
    CATALOG_POC_ARCH="${CATALOG_POC_ARCH:-amd64}"
    ;;
  *)
    CATALOG_POC_ARCH="${CATALOG_POC_ARCH:-$(uname -m)}"
    ;;
esac

CATALOG_POC_BUILD_DIR="${CATALOG_POC_BUILD_DIR:-build/catalog-poc}"
CATALOG_POC_PACKAGE_DIR="${CATALOG_POC_PACKAGE_DIR:-examples/catalog-poc}"
CATALOG_POC_PACKAGE_ARCHIVE="${CATALOG_POC_PACKAGE_ARCHIVE:-build/zarf-package-${CATALOG_POC_NAME}-${CATALOG_POC_ARCH}-${CATALOG_POC_VERSION}.tar.zst}"
CATALOG_POC_PLAIN_HTTP_FLAG=()

if [[ "${CATALOG_POC_REGISTRY}" == localhost:* || "${CATALOG_POC_REGISTRY}" == 127.0.0.1:* ]]; then
  CATALOG_POC_PLAIN_HTTP_FLAG=(--plain-http)
fi

export CATALOG_POC_ARCH
export CATALOG_POC_BUILD_DIR
export CATALOG_POC_IMAGE
export CATALOG_POC_NAME
export CATALOG_POC_OCI_REF
export CATALOG_POC_PACKAGE_ARCHIVE
export CATALOG_POC_PACKAGE_DIR
export CATALOG_POC_REGISTRY
export CATALOG_POC_REPOSITORY
export CATALOG_POC_VERSION
