#!/usr/bin/env bash
set -euo pipefail

cluster_name="${UDS_K3D_CLUSTER_NAME:-uds}"
serverlb_name="k3d-${cluster_name}-serverlb"
server_node="k3d-${cluster_name}-server-0"
agent_node="k3d-${cluster_name}-agent-0"

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 is required." >&2
    exit 1
  fi
}

node_port() {
  local namespace="$1"
  local service="$2"
  local port_name="$3"

  kubectl -n "$namespace" get svc "$service" \
    -o jsonpath="{.spec.ports[?(@.name==\"${port_name}\")].nodePort}"
}

require docker
require kubectl

if ! docker ps --format '{{.Names}}' | grep -qx "$serverlb_name"; then
  echo "k3d server load balancer ${serverlb_name} is not running." >&2
  exit 1
fi

tenant_http_port="$(node_port istio-tenant-gateway tenant-ingressgateway http2)"
tenant_https_port="$(node_port istio-tenant-gateway tenant-ingressgateway https)"
admin_http_port="$(node_port istio-admin-gateway admin-ingressgateway http2 2>/dev/null || true)"
admin_https_port="$(node_port istio-admin-gateway admin-ingressgateway https 2>/dev/null || true)"

if [ -z "$tenant_http_port" ] || [ -z "$tenant_https_port" ]; then
  echo "Could not discover tenant gateway NodePorts." >&2
  exit 1
fi

admin_http_port="${admin_http_port:-$tenant_http_port}"
admin_https_port="${admin_https_port:-$tenant_https_port}"

tmp_conf="$(mktemp)"
trap 'rm -f "$tmp_conf"' EXIT

cat >"$tmp_conf" <<EOF
#############################################
# Generated by scripts/fix-uds-gateway-routing.sh
# Routes macOS workaround host ports to UDS gateway NodePorts.
#############################################

error_log stderr notice;

worker_processes auto;
events {
  multi_accept on;
  use epoll;
  worker_connections 1024;
}

stream {
  map \$ssl_preread_server_name \$https_gateway {
    ~\\.admin\\.uds\\.dev\$ admin_https;
    default tenant_https;
  }

  upstream api_server {
    server ${server_node}:6443 max_fails=1 fail_timeout=10s;
  }

  upstream tenant_https {
    server ${agent_node}:${tenant_https_port} max_fails=1 fail_timeout=10s;
    server ${server_node}:${tenant_https_port} max_fails=1 fail_timeout=10s;
  }

  upstream admin_https {
    server ${agent_node}:${admin_https_port} max_fails=1 fail_timeout=10s;
    server ${server_node}:${admin_https_port} max_fails=1 fail_timeout=10s;
  }

  server {
    listen 6443;
    proxy_pass api_server;
    proxy_timeout 600;
    proxy_connect_timeout 2s;
  }

  server {
    listen 443;
    ssl_preread on;
    proxy_pass \$https_gateway;
    proxy_timeout 600;
    proxy_connect_timeout 2s;
  }
}

http {
  map \$host \$http_gateway {
    ~\\.admin\\.uds\\.dev\$ admin_http;
    default tenant_http;
  }

  upstream tenant_http {
    server ${agent_node}:${tenant_http_port} max_fails=1 fail_timeout=10s;
    server ${server_node}:${tenant_http_port} max_fails=1 fail_timeout=10s;
  }

  upstream admin_http {
    server ${agent_node}:${admin_http_port} max_fails=1 fail_timeout=10s;
    server ${server_node}:${admin_http_port} max_fails=1 fail_timeout=10s;
  }

  server {
    listen 80;

    location / {
      proxy_set_header Host \$host;
      proxy_set_header X-Forwarded-Host \$host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_pass http://\$http_gateway;
    }
  }
}
EOF

echo "Patching ${serverlb_name} routing:"
echo "  tenant http : host 80  -> NodePort ${tenant_http_port}"
echo "  tenant https: host 443 -> NodePort ${tenant_https_port}"
echo "  admin http  : host 80  -> NodePort ${admin_http_port}"
echo "  admin https : host 443 -> NodePort ${admin_https_port}"

docker exec "$serverlb_name" cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.k3d-original >/dev/null 2>&1 || true
docker cp "$tmp_conf" "${serverlb_name}:/etc/nginx/nginx.conf"
docker exec "$serverlb_name" nginx -t
docker exec "$serverlb_name" nginx -s reload

echo "UDS gateway routing patched on ${serverlb_name}."
